//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_CONTACTO
    {
        public int ID_MENSAJE { get; set; }
        public string TIPO_MENSAJE { get; set; }
        public string EMISOR { get; set; }
        public string CORREO_EMISOR { get; set; }
        public string CUERPO_CORREO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
    }
}
