//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_CONTACTO
    {
        public int ID_MENSAJE { get; set; }
        public string TIPO_MENSAJE { get; set; }
        public string EMISOR { get; set; }
        public string CORREO_EMISOR { get; set; }
        public string CUERPO_CORREO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
    }
}
