//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public long IdCarrito { get; set; }
        public long ConsecutivoUsuario { get; set; }
        public int ConsecutivoHospedaje { get; set; }
        public int CantNoches { get; set; }
        public double Precio { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
    
        public virtual HOSPEDAJE HOSPEDAJE { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
