//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE
    {
        public long IdDetalle { get; set; }
        public long IdMaestro { get; set; }
        public int CantNoches { get; set; }
        public decimal Precio { get; set; }
        public int ConsecutivoHospedaje { get; set; }
    
        public virtual DETALLE DETALLE1 { get; set; }
        public virtual DETALLE DETALLE2 { get; set; }
        public virtual HOSPEDAJE HOSPEDAJE { get; set; }
        public virtual MAESTRO MAESTRO { get; set; }
    }
}
