//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPEDAJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSPEDAJE()
        {
            this.CARRITO = new HashSet<CARRITO>();
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public int ConsecutivoHospedaje { get; set; }
        public string Nombre { get; set; }
        public byte CodProvincia { get; set; }
        public double Precio { get; set; }
        public string Disponibilidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<long> ConsecutivoUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO> CARRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual PROVINCIAS PROVINCIAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
