//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAESTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAESTRO()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public long IdMaestro { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public long ConsecutivoUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
