//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoW_BDEntities : DbContext
    {
        public ProyectoW_BDEntities()
            : base("name=ProyectoW_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORA_CONTACTO> BITACORA_CONTACTO { get; set; }
        public virtual DbSet<BITACORAS> BITACORAS { get; set; }
        public virtual DbSet<CARRITO> CARRITO { get; set; }
        public virtual DbSet<DETALLE> DETALLE { get; set; }
        public virtual DbSet<ERRORES> ERRORES { get; set; }
        public virtual DbSet<HOSPEDAJE> HOSPEDAJE { get; set; }
        public virtual DbSet<MAESTRO> MAESTRO { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<RESERVAS> RESERVAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual int ConfirmarPago(Nullable<long> consecutivoUsuario)
        {
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfirmarPago", consecutivoUsuarioParameter);
        }
    
        public virtual ObjectResult<MostrarCarritoTemporal_Result> MostrarCarritoTemporal(Nullable<long> consecutivoUsuario)
        {
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarCarritoTemporal_Result>("MostrarCarritoTemporal", consecutivoUsuarioParameter);
        }
    
        public virtual ObjectResult<MostrarCarritoTotal_Result> MostrarCarritoTotal(Nullable<long> consecutivoUsuario)
        {
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarCarritoTotal_Result>("MostrarCarritoTotal", consecutivoUsuarioParameter);
        }
    
        public virtual ObjectResult<MostrarFacturas_Result> MostrarFacturas(Nullable<long> consecutivoUsuario)
        {
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarFacturas_Result>("MostrarFacturas", consecutivoUsuarioParameter);
        }
    
        public virtual ObjectResult<obtenerHospedajesConNombreProvincia_Result> obtenerHospedajesConNombreProvincia(int q)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtenerHospedajesConNombreProvincia_Result>("obtenerHospedajesConNombreProvincia");
        }
    
        public virtual ObjectResult<obtenerHospedajesPorUsuario_Result> obtenerHospedajesPorUsuario(Nullable<int> consecutivoUsuario)
        {
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtenerHospedajesPorUsuario_Result>("obtenerHospedajesPorUsuario", consecutivoUsuarioParameter);
        }
    
        public virtual int RegistrarBitacora(string descripcion, string origen)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarBitacora", descripcionParameter, origenParameter);
        }
    
        public virtual ObjectResult<ValidarUsuario_Result> ValidarUsuario(string correoElectronico, string contrasenna)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidarUsuario_Result>("ValidarUsuario", correoElectronicoParameter, contrasennaParameter);
        }
    }
}
