//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoApi_KN.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        public long ConsecutivoReservas { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public long CodUsuario { get; set; }
        public long CodDestino { get; set; }
        public bool Pago { get; set; }
        public bool Estado { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
